admin_orders_place:
  path: /sell/orders/orders/place
  methods: [ POST ]
  defaults:
    _controller: 'GraphicCustomManager\Controller\Admin\OrderController::placeAction'
    _disable_module_prefix: true
